//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K2_Generate_Package_Code_15_Digit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class C5PackageCode
    {
        public int id { get; set; }
        public string fullcode { get; set; }
        public string code1 { get; set; }
        public string code2 { get; set; }
        public string code3 { get; set; }
        public string code4 { get; set; }
        public string code5 { get; set; }
    }
}
