//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K2_Generate_Package_Code_15_Digit.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageHeight
    {
        public int Id { get; set; }
        public Nullable<decimal> Mold { get; set; }
        public Nullable<decimal> Frame { get; set; }
        public string Substrate { get; set; }
        public string Code { get; set; }
    }
}
